// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjwcpjfcpjeljosrkrfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqd2NwamZjcGplbGpvc3JrcmZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTU0MzAsImV4cCI6MjA2NzAzMTQzMH0.Js4yp3CfTWFeFzU1G-mpg1ZooEPqG8RkDrpYj_ajvgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});